//原始代码在"处理qn_scopus_pub申请部门问题.do"
//用于处理青年项目基金申请人scopus发表数据中申请部门的问题
//青年项目基金申请人scopus发表数据的stata版本在qn_scopusPub_all.dta


cap drop 申请部门估
g 申请部门估=school1
replace 申请部门估="" if strpos(school1," FOUND")|strpos(school1,"no")|strpos(school1,"TBD")|strpos(school1,"搜出来")|strpos(school1,"查不到")|strpos(school1,"查出来")|strpos(school1,"搜不出来")|strpos(school1,"非山大")
replace 申请部门估="齐鲁医学院" if school1=="Cheeloo College of Medicine"
replace 申请部门估="岩土与结构工程研究中心" if school1=="Geotechnical and Structural Engineering Research Center"
replace 申请部门估="岩土与结构工程研究中心" if school1=="Research Center of Geotechnical and Structural Engineering"
replace 申请部门估="济南市中心医院" if school1=="中心医院"|school1=="市中心医院"|school1=="附属中心医院"|school1=="附属中心医院（济南市中心医院）"
replace 申请部门估="省立医院" if strpos(school1,"省立医院 ")
replace 申请部门估="基础医学院" if strpos(school1,"j基础医学院")
replace 申请部门估="省立第三医院" if strpos(school1,"s省立第三医院")|school1=="山东省立第三医院"
replace 申请部门估="公共卫生学院" if school1=="公共卫生学院 "
replace 申请部门估="机械工程学院" if school1=="机械工程学院 "
replace 申请部门估="软件学院" if school1=="软件学院 "
replace 申请部门估="环境研究院" if school1=="环境研究院 "
replace 申请部门估="齐鲁医学院" if school1=="齐鲁医学院 "
replace 申请部门估="信息科学与工程学院" if school1=="信息科学与工程"|school1=="信息学院"
replace 申请部门估="前沿交叉科学青岛研究院" if school1=="前沿交叉研究院"|school1=="前沿交叉科学院"
replace 申请部门估="化学与化工学院" if school1=="化学学院"|school1=="化学院"|school1=="化工学院"
replace 申请部门估="口腔医学院" if school1=="口腔药学院"
replace 申请部门估="国家糖工程技术研究中心" if school1=="国家糖工程技术研究中心"
replace 申请部门估="中泰金融研究院" if school1=="中泰证券金融研究院"
replace 申请部门估="高等医学研究院" if school1=="医学研究院"
replace 申请部门估="土建与水利学院" if school1=="土木工程学院"
replace 申请部门估="微生物技术国家重点实验室" if school1=="山东大学微生物技术国家重点实验室"|school1=="微生物技术研究所"|school1=="微生物技术研究院"
replace 申请部门估="政治学与公共管理学院" if school1=="山东大学政治学与公共管理学院"
replace 申请部门估="胶体与界面化学教育部重点实验室" if school1=="山东大学胶体与界面化学教育部重点实验室"
replace 申请部门估="岩土与结构工程研究中心" if school1=="岩土工程与结构工程研究中心"
replace 申请部门估="护理与康复学院" if school1=="护理学院"
replace 申请部门估="控制科学与工程学院" if school1=="控制科学与工程"
replace 申请部门估="政治学与公共管理学院" if school1=="政治与公共事务管理学院"
replace 申请部门估="材料科学与工程学院" if school1=="材料与工程学院"|school1=="材料科学与工程"
replace 申请部门估="淄博市中心医院" if school1=="淄博中心医院"
replace 申请部门估="环境科学与工程学院" if school1=="环境工程与科学学院"|school1=="环境科学与工程"
replace 申请部门估="环境研究院" if school1=="环境研究所"
replace 申请部门估="生命科学学院" if school1=="生命科学学院发育生物学研究所"|school1=="生命科学院"
replace 申请部门估="山大二院" if school1=="第二医院"
replace 申请部门估="能源与动力工程学院" if school1=="能源与动力学院"|school1=="能源动力与工程学院"|school1=="能源动力工程学院"
replace 申请部门估="计算机科学与技术学院" if school1=="计算机科学与工程学院"|school1=="计算机科学与技术"|school1=="计算机科学与技术学院系统结构研究所"
replace 申请部门估="医学院" if school1=="中科院系统生物学重点实验室"
replace 申请部门估="化学与环境科学学院" if school1=="化学与环境学院"
replace 申请部门估="基础医学院" if school1=="医学院生物化学与分子生物学系"
replace 申请部门估="岩土与结构工程研究中心" if school1=="地质科学中心"|school1=="岩土工程与结构工程研究中心"|school1=="地质科技中心"
replace 申请部门估="电气工程学院" if school1=="教育学院"
replace 申请部门估="微电子学院" if school1=="材料科学与工程学院（西安大学）"
replace 申请部门估="海洋学院" if school1=="海洋生命学院"
replace 申请部门估="海洋研究院" if school1=="海洋科学与工程学院"
replace 申请部门估="光学高等研究中心" if school1=="激光研究所"
replace 申请部门估="材料液固结构演变与加工教育部重点实验室" if school1=="物理工程学院"
replace 申请部门估="药学院" if school1=="生化工程国家重点实验室"
replace 申请部门估="齐鲁医学院" if school1=="生物工程学院"
replace 申请部门估="微生物技术国家重点实验室" if school1=="生物科学与技术学院"
replace 申请部门估="中泰金融研究院" if school1=="金融研究院"
replace 申请部门估="晶体材料国家重点实验室" if school1=="晶体材料研究所"
replace 申请部门估="热科学与工程研究中心" if school1=="热科学研究中心"
replace 申请部门估="微生物技术国家重点实验室" if school1=="寰敓鐗╂妧鏈浗瀹堕噸鐐瑰疄楠屽"
replace 申请部门估="齐鲁医院" if school1=="榻愰瞾鍖婚櫌"
replace 申请部门估="山东省耳鼻喉科医院" if school1=="榻愰瞾鍖诲闄?"
replace 申请部门估="齐鲁医学院" if school1=="榻愰瞾鍖诲闄?榻愰瞾鍖婚櫌"
replace 申请部门估="信息科学与工程学院" if school1=="淇℃伅绉戝涓庡伐绋嬪闄?"
replace 申请部门估="化学与化工学院" if school1=="鍖栧涓庡寲宸ュ闄?"
replace 申请部门估="土建与水利学院" if school1=="鍦熸湪宸ョ▼瀛﹂櫌"
replace 申请部门估="文化遗产研究院" if school1=="鏂囧寲閬椾骇鐮旂┒闄?"
replace 申请部门估="晶体材料国家重点实验室" if school1=="鏅朵綋鏉愭枡鍥藉閲嶇偣瀹為獙瀹?"
replace 申请部门估="化学与化工学院" if school1=="鏅朵綋鏉愭枡鍥藉閲嶇偣瀹為獙瀹?鍖栧涓庡寲宸ュ闄?"
replace 申请部门估="化学与化工学院" if school1=="鏅朵綋鏉愭枡鍥藉閲嶇偣瀹為獙瀹?鍖栧闄?"
replace 申请部门估="材料科学与工程学院" if school1=="鏉愭枡绉戝涓庡伐绋嬪闄?"
replace 申请部门估="环境科学与工程学院" if school1=="鐜绉戝涓庡伐绋嬪闄?"
replace 申请部门估="电气工程学院" if school1=="鐢垫皵宸ョ▼瀛﹂櫌"
replace 申请部门估="省立医院" if school1=="鐪佺珛鍖婚櫌"
replace 申请部门估="岩土与结构工程研究中心" if school1=="岩土工程中心"
replace 申请部门估="附属儿童医院" if school1=="齐鲁儿童医院"
*save qn_scopusPub_all.dta, replace